      SUBROUTINE DE_ALLOCATE
!$$$  SUBPROGRAM DOCUMENTATION BLOCK
!                .      .    .
! SUBPROGRAM:    MPI_FIRST   SET UP MESSGAE PASSING INFO
!   PRGRMMR: TUCCILLO        ORG: IBM
!
! ABSTRACT:
!     SETS UP MESSAGE PASSING INFO
!   .
!
! PROGRAM HISTORY LOG:
!   00-01-06  TUCCILLO - ORIGINAL
!   01-10-25  H CHUANG - MODIFIED TO PROCESS HYBRID MODEL OUTPUT
!   02-06-19  MIKE BALDWIN - WRF VERSION
!
! USAGE:    CALL MPI_FIRST
!   INPUT ARGUMENT LIST:
!
!   OUTPUT ARGUMENT LIST:
!
!   OUTPUT FILES:
!     STDOUT  - RUN TIME STANDARD OUT.
!
!   SUBPROGRAMS CALLED:
!       PARA_RANGE
!     UTILITIES:
!       NONE
!     LIBRARY:
!       COMMON - CTLBLK.comm
!
!   ATTRIBUTES:
!     LANGUAGE: FORTRAN
!     MACHINE : IBM RS/6000 SP
!$$$
!
      use vrbls4d
      use vrbls3d
      use vrbls2d
      use soil
      use masks
      use params_mod
      use ctlblk_mod
!- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - 
!
       implicit none
!
      include 'mpif.h'
!
!
!     deallocate arrays
!
!
!     FROM VRBLS3D
!
      if(allocated(acswdnt)) deallocate(u)
      if(allocated(acswdnt)) deallocate(v)
      if(allocated(acswdnt)) deallocate(t)
! CHUANG ADD POTENTIAL TEMP BECAUSE WRF OUTPUT THETA
!      if(allocated(acswdnt)) deallocate(th)   
      if(allocated(acswdnt)) deallocate(q)
!      if(allocated(acswdnt)) deallocate(w(im,jsta_2l:jend_2u,lp1))
      if(allocated(acswdnt)) deallocate(uh)
      if(allocated(acswdnt)) deallocate(vh)
      if(allocated(acswdnt)) deallocate(wh)
      if(allocated(acswdnt)) deallocate(pmid)
      if(allocated(acswdnt)) deallocate(pmidv)
      if(allocated(acswdnt)) deallocate(pint)
      if(allocated(acswdnt)) deallocate(alpint)
      if(allocated(acswdnt)) deallocate(zmid)
      if(allocated(acswdnt)) deallocate(zint)
!      if(allocated(acswdnt)) deallocate(rainw(im,jsta_2l:jend_2u,lm))
      if(allocated(acswdnt)) deallocate(q2)
      if(allocated(acswdnt)) deallocate(omga)
      if(allocated(acswdnt)) deallocate(T_ADJ)
      if(allocated(acswdnt)) deallocate(ttnd)
      if(allocated(acswdnt)) deallocate(rswtt)
      if(allocated(acswdnt)) deallocate(rlwtt)
      if(allocated(acswdnt)) deallocate(exch_h) 
      if(allocated(acswdnt)) deallocate(train)
      if(allocated(acswdnt)) deallocate(tcucn)
      if(allocated(acswdnt)) deallocate(EL_PBL)
!     MP FIELD   
      if(allocated(acswdnt)) deallocate(cwm)
      if(allocated(acswdnt)) deallocate(F_ice)
      if(allocated(acswdnt)) deallocate(F_rain)
      if(allocated(acswdnt)) deallocate(F_RimeF)
      if(allocated(acswdnt)) deallocate(QQW)
      if(allocated(acswdnt)) deallocate(QQI)
      if(allocated(acswdnt)) deallocate(QQR)
      if(allocated(acswdnt)) deallocate(QQS)
      if(allocated(acswdnt)) deallocate(QQG)
      if(allocated(acswdnt)) deallocate(QQNW)
      if(allocated(acswdnt)) deallocate(QQNI)
      if(allocated(acswdnt)) deallocate(QQNR)
      if(allocated(acswdnt)) deallocate(QQNWFA)
      if(allocated(acswdnt)) deallocate(QQNIFA)
      if(allocated(acswdnt)) deallocate(TAOD5503D)
      if(allocated(acswdnt)) deallocate(AEXTC55)
      if(allocated(acswdnt)) deallocate(EXTCOF55)
      if(allocated(acswdnt)) deallocate(CFR)
      if(allocated(acswdnt)) deallocate(CFR_RAW)
      if(allocated(acswdnt)) deallocate(DBZ)
      if(allocated(acswdnt)) deallocate(DBZR)
      if(allocated(acswdnt)) deallocate(DBZI)
      if(allocated(acswdnt)) deallocate(DBZC)
      if(allocated(acswdnt)) deallocate(mcvg)
      if(allocated(acswdnt)) deallocate(NLICE)
!     Wm Lewis: added
      if(allocated(acswdnt)) deallocate(NRAIN)
      if(allocated(acswdnt)) deallocate(radius_cloud)
      if(allocated(acswdnt)) deallocate(radius_ice)
      if(allocated(acswdnt)) deallocate(radius_snow)
!GFS FIELD
      if(allocated(acswdnt)) deallocate(o3)
      if(allocated(acswdnt)) deallocate(o)
      if(allocated(acswdnt)) deallocate(o2)
      if(allocated(acswdnt)) deallocate(tcucns)
! Add GFS d3d fields
      if (d3d_on) then
        if(allocated(acswdnt)) deallocate(vdifftt)
!       if(allocated(acswdnt)) deallocate(tcucns)
        if(allocated(acswdnt)) deallocate(vdiffmois)
        if(allocated(acswdnt)) deallocate(dconvmois)
        if(allocated(acswdnt)) deallocate(sconvmois)
        if(allocated(acswdnt)) deallocate(nradtt)
        if(allocated(acswdnt)) deallocate(o3vdiff)
        if(allocated(acswdnt)) deallocate(o3prod)
        if(allocated(acswdnt)) deallocate(o3tndy)
        if(allocated(acswdnt)) deallocate(mwpv)
        if(allocated(acswdnt)) deallocate(unknown)
        if(allocated(acswdnt)) deallocate(vdiffzacce)
        if(allocated(acswdnt)) deallocate(zgdrag)
        if(allocated(acswdnt)) deallocate(cnvctummixing)
        if(allocated(acswdnt)) deallocate(vdiffmacce)
        if(allocated(acswdnt)) deallocate(mgdrag)
        if(allocated(acswdnt)) deallocate(cnvctvmmixing)
        if(allocated(acswdnt)) deallocate(ncnvctcfrac)
        if(allocated(acswdnt)) deallocate(cnvctumflx)
        if(allocated(acswdnt)) deallocate(cnvctdmflx)
        if(allocated(acswdnt)) deallocate(cnvctdetmflx)
        if(allocated(acswdnt)) deallocate(cnvctzgdrag)
        if(allocated(acswdnt)) deallocate(cnvctmgdrag)      
      endif
!
!     FROM SOIL
!
      if(allocated(acswdnt)) deallocate(smc)
      if(allocated(acswdnt)) deallocate(stc)
      if(allocated(acswdnt)) deallocate(erod)
      if(allocated(acswdnt)) deallocate(sh2o)
      if(allocated(acswdnt)) deallocate(SLDPTH)
      if(allocated(acswdnt)) deallocate(RTDPTH)
      if(allocated(acswdnt)) deallocate(SLLEVEL)
!
!     FROM VRBLS2D
!
      if(allocated(acswdnt)) deallocate(u10)
      if(allocated(acswdnt)) deallocate(v10)
      if(allocated(acswdnt)) deallocate(tshltr)
      if(allocated(acswdnt)) deallocate(qshltr)
      if(allocated(acswdnt)) deallocate(mrshltr)
      if(allocated(acswdnt)) deallocate(smstav)
      if(allocated(acswdnt)) deallocate(ssroff)
      if(allocated(acswdnt)) deallocate(bgroff)
      if(allocated(acswdnt)) deallocate(vegfrc)
      if(allocated(acswdnt)) deallocate(acsnow)
      if(allocated(acswdnt)) deallocate(acgraup)
      if(allocated(acswdnt)) deallocate(acfrain)
      if(allocated(acswdnt)) deallocate(acsnom)
      if(allocated(acswdnt)) deallocate(cmc)
      if(allocated(acswdnt)) deallocate(sst)
      if(allocated(acswdnt)) deallocate(qz0)
      if(allocated(acswdnt)) deallocate(thz0)
      if(allocated(acswdnt)) deallocate(uz0)
      if(allocated(acswdnt)) deallocate(vz0)
      if(allocated(acswdnt)) deallocate(qs)
      if(allocated(acswdnt)) deallocate(ths)
      if(allocated(acswdnt)) deallocate(sno)
      if(allocated(acswdnt)) deallocate(snonc)
      if(allocated(acswdnt)) deallocate(snoavg)
      if(allocated(acswdnt)) deallocate(psfcavg)
      if(allocated(acswdnt)) deallocate(t10m)
      if(allocated(acswdnt)) deallocate(t10avg)
      if(allocated(acswdnt)) deallocate(akhsavg)
      if(allocated(acswdnt)) deallocate(akmsavg)
      if(allocated(acswdnt)) deallocate(u10max)
      if(allocated(acswdnt)) deallocate(v10max)
      if(allocated(acswdnt)) deallocate(u10h)
      if(allocated(acswdnt)) deallocate(v10h)
      if(allocated(acswdnt)) deallocate(akms)
      if(allocated(acswdnt)) deallocate(akhs)
      if(allocated(acswdnt)) deallocate(cuprec)
      if(allocated(acswdnt)) deallocate(acprec)
      if(allocated(acswdnt)) deallocate(ancprc)
      if(allocated(acswdnt)) deallocate(cuppt)
      if(allocated(acswdnt)) deallocate(tsnow)
      if(allocated(acswdnt)) deallocate(qvg)
      if(allocated(acswdnt)) deallocate(qv2m)
      if(allocated(acswdnt)) deallocate(rswin)
      if(allocated(acswdnt)) deallocate(swddni)
      if(allocated(acswdnt)) deallocate(swddif)
      if(allocated(acswdnt)) deallocate(swdnbc)
      if(allocated(acswdnt)) deallocate(swupbc)
      if(allocated(acswdnt)) deallocate(swddnic)
      if(allocated(acswdnt)) deallocate(swddifc)
      if(allocated(acswdnt)) deallocate(swupt)
      if(allocated(acswdnt)) deallocate(int_smoke)
      if(allocated(acswdnt)) deallocate(mean_frp)
      if(allocated(acswdnt)) deallocate(int_aod)
      if(allocated(acswdnt)) deallocate(smoke)
      if(allocated(acswdnt)) deallocate(plume)
      if(allocated(acswdnt)) deallocate(taod5502d)
      if(allocated(acswdnt)) deallocate(aerasy2d)
      if(allocated(acswdnt)) deallocate(aerssa2d)
      if(allocated(acswdnt)) deallocate(lwp)
      if(allocated(acswdnt)) deallocate(iwp)
      if(allocated(acswdnt)) deallocate(rlwin)
      if(allocated(acswdnt)) deallocate(lwdnbc)
      if(allocated(acswdnt)) deallocate(lwupbc)
      if(allocated(acswdnt)) deallocate(rlwtoa)
      if(allocated(acswdnt)) deallocate(rswtoa)
      if(allocated(acswdnt)) deallocate(tg)
      if(allocated(acswdnt)) deallocate(sfcshx)
      if(allocated(acswdnt)) deallocate(sfclhx)
      if(allocated(acswdnt)) deallocate(fis)
      if(allocated(acswdnt)) deallocate(t500)
      if(allocated(acswdnt)) deallocate(cfracl)
      if(allocated(acswdnt)) deallocate(cfracm)
      if(allocated(acswdnt)) deallocate(cfrach)
      if(allocated(acswdnt)) deallocate(acfrst)
      if(allocated(acswdnt)) deallocate(acfrcv)
      if(allocated(acswdnt)) deallocate(hbot)
      if(allocated(acswdnt)) deallocate(htop)
      if(allocated(acswdnt)) deallocate(aswin)
      if(allocated(acswdnt)) deallocate(alwin)
      if(allocated(acswdnt)) deallocate(aswout)
      if(allocated(acswdnt)) deallocate(alwout)
      if(allocated(acswdnt)) deallocate(aswtoa)
      if(allocated(acswdnt)) deallocate(alwtoa)
      if(allocated(acswdnt)) deallocate(czen)
      if(allocated(acswdnt)) deallocate(czmean)
      if(allocated(acswdnt)) deallocate(sigt4)
      if(allocated(acswdnt)) deallocate(rswout)
      if(allocated(acswdnt)) deallocate(radot)
      if(allocated(acswdnt)) deallocate(ncfrst)  ! real
      if(allocated(acswdnt)) deallocate(ncfrcv)  ! real
      if(allocated(acswdnt)) deallocate(smstot)
      if(allocated(acswdnt)) deallocate(pctsno)
      if(allocated(acswdnt)) deallocate(pshltr)
      if(allocated(acswdnt)) deallocate(th10)
      if(allocated(acswdnt)) deallocate(q10)
      if(allocated(acswdnt)) deallocate(sr)
      if(allocated(acswdnt)) deallocate(prec)
      if(allocated(acswdnt)) deallocate(subshx)
      if(allocated(acswdnt)) deallocate(snopcx)
      if(allocated(acswdnt)) deallocate(sfcuvx)
      if(allocated(acswdnt)) deallocate(sfcevp)
      if(allocated(acswdnt)) deallocate(potevp)
      if(allocated(acswdnt)) deallocate(z0)
      if(allocated(acswdnt)) deallocate(ustar)
      if(allocated(acswdnt)) deallocate(pblh)
      if(allocated(acswdnt)) deallocate(pblhgust)
      if(allocated(acswdnt)) deallocate(twbs)
      if(allocated(acswdnt)) deallocate(qwbs)
      if(allocated(acswdnt)) deallocate(sfcexc)
      if(allocated(acswdnt)) deallocate(grnflx)
      if(allocated(acswdnt)) deallocate(soiltb)
      if(allocated(acswdnt)) deallocate(z1000)
      if(allocated(acswdnt)) deallocate(slp)
      if(allocated(acswdnt)) deallocate(pslp)
      if(allocated(acswdnt)) deallocate(f)
      if(allocated(acswdnt)) deallocate(albedo)
      if(allocated(acswdnt)) deallocate(albase)
      if(allocated(acswdnt)) deallocate(cldfra)
      if(allocated(acswdnt)) deallocate(cprate)
      if(allocated(acswdnt)) deallocate(cnvcfr)
      if(allocated(acswdnt)) deallocate(ivgtyp)
      if(allocated(acswdnt)) deallocate(isltyp)
      if(allocated(acswdnt)) deallocate(hbotd)
      if(allocated(acswdnt)) deallocate(htopd)
      if(allocated(acswdnt)) deallocate(hbots)
      if(allocated(acswdnt)) deallocate(htops)
      if(allocated(acswdnt)) deallocate(cldefi)
      if(allocated(acswdnt)) deallocate(islope)
      if(allocated(acswdnt)) deallocate(si)
      if(allocated(acswdnt)) deallocate(lspa)
      if(allocated(acswdnt)) deallocate(rswinc)
      if(allocated(acswdnt)) deallocate(vis)
      if(allocated(acswdnt)) deallocate(pd)
      if(allocated(acswdnt)) deallocate(mxsnal)
! add GFS fields
      if(allocated(acswdnt)) deallocate(sfcux)
      if(allocated(acswdnt)) deallocate(sfcvx)
      if(allocated(acswdnt)) deallocate(sfcuxi)
      if(allocated(acswdnt)) deallocate(sfcvxi)
      if(allocated(acswdnt)) deallocate(avgalbedo)
      if(allocated(acswdnt)) deallocate(avgcprate)
      if(allocated(acswdnt)) deallocate(avgprec)
      if(allocated(acswdnt)) deallocate(avgprec_cont)
      if(allocated(acswdnt)) deallocate(avgcprate_cont)
      if(allocated(acswdnt)) deallocate(ptop)
      if(allocated(acswdnt)) deallocate(pbot)
      if(allocated(acswdnt)) deallocate(avgcfrach)
      if(allocated(acswdnt)) deallocate(avgcfracm)
      if(allocated(acswdnt)) deallocate(avgcfracl)
      if(allocated(acswdnt)) deallocate(avgtcdc)
      if(allocated(acswdnt)) deallocate(auvbin)
      if(allocated(acswdnt)) deallocate(auvbinc)
      if(allocated(acswdnt)) deallocate(ptopl)
      if(allocated(acswdnt)) deallocate(pbotl)
      if(allocated(acswdnt)) deallocate(Ttopl)
      if(allocated(acswdnt)) deallocate(ptopm)
      if(allocated(acswdnt)) deallocate(pbotm)
      if(allocated(acswdnt)) deallocate(Ttopm)
      if(allocated(acswdnt)) deallocate(ptoph)
      if(allocated(acswdnt)) deallocate(pboth)
      if(allocated(acswdnt)) deallocate(Ttoph)
      if(allocated(acswdnt)) deallocate(sfcugs)
      if(allocated(acswdnt)) deallocate(sfcvgs)
      if(allocated(acswdnt)) deallocate(pblcfr)
      if(allocated(acswdnt)) deallocate(cldwork)
      if(allocated(acswdnt)) deallocate(gtaux)
      if(allocated(acswdnt)) deallocate(gtauy)
      if(allocated(acswdnt)) deallocate(mdltaux)
      if(allocated(acswdnt)) deallocate(mdltauy)
      if(allocated(acswdnt)) deallocate(runoff)
      if(allocated(acswdnt)) deallocate(maxtshltr)
      if(allocated(acswdnt)) deallocate(mintshltr)
      if(allocated(acswdnt)) deallocate(maxrhshltr)
      if(allocated(acswdnt)) deallocate(minrhshltr)
      if(allocated(acswdnt)) deallocate(maxqshltr)
      if(allocated(acswdnt)) deallocate(minqshltr)
      if(allocated(acswdnt)) deallocate(mixht)
      if(allocated(acswdnt)) deallocate(epsr)
      if(allocated(acswdnt)) deallocate(dzice)
      if(allocated(acswdnt)) deallocate(alwinc)
      if(allocated(acswdnt)) deallocate(alwoutc)
      if(allocated(acswdnt)) deallocate(alwtoac)
      if(allocated(acswdnt)) deallocate(aswinc)
      if(allocated(acswdnt)) deallocate(aswoutc)
      if(allocated(acswdnt)) deallocate(aswtoac)
      if(allocated(acswdnt)) deallocate(aswintoa)
      if(allocated(acswdnt)) deallocate(smcwlt)
      if(allocated(acswdnt)) deallocate(suntime)
      if(allocated(acswdnt)) deallocate(fieldcapa)
      if(allocated(acswdnt)) deallocate(avisbeamswin)
      if(allocated(acswdnt)) deallocate(avisdiffswin)
      if(allocated(acswdnt)) deallocate(airbeamswin)
      if(allocated(acswdnt)) deallocate(airdiffswin)
      if(allocated(acswdnt)) deallocate(snowfall)
      if(allocated(acswdnt)) deallocate(acond)
      if(allocated(acswdnt)) deallocate(edir)
      if(allocated(acswdnt)) deallocate(ecan)
      if(allocated(acswdnt)) deallocate(etrans)
      if(allocated(acswdnt)) deallocate(esnow)
      if(allocated(acswdnt)) deallocate(avgedir)
      if(allocated(acswdnt)) deallocate(avgecan)
      if(allocated(acswdnt)) deallocate(avgetrans)
      if(allocated(acswdnt)) deallocate(avgesnow)
      if(allocated(acswdnt)) deallocate(avgpotevp)
      if(allocated(acswdnt)) deallocate(ti)
! GSD
      if(allocated(acswdnt)) deallocate(rainc_bucket)
      if(allocated(acswdnt)) deallocate(rainnc_bucket)
      if(allocated(acswdnt)) deallocate(pcp_bucket)
      if(allocated(acswdnt)) deallocate(snow_bucket)
      if(allocated(acswdnt)) deallocate(graup_bucket)
      if(allocated(acswdnt)) deallocate(qrmax)
      if(allocated(acswdnt)) deallocate(tmax)
      if(allocated(acswdnt)) deallocate(snownc)
      if(allocated(acswdnt)) deallocate(graupelnc)
! SRD
      if(allocated(acswdnt)) deallocate(wspd10max)
      if(allocated(acswdnt)) deallocate(w_up_max)
      if(allocated(acswdnt)) deallocate(w_dn_max)
      if(allocated(acswdnt)) deallocate(w_mean)
      if(allocated(acswdnt)) deallocate(refd_max)
      if(allocated(acswdnt)) deallocate(prate_max)
      if(allocated(acswdnt)) deallocate(fprate_max)
      if(allocated(acswdnt)) deallocate(up_heli_max)
      if(allocated(acswdnt)) deallocate(up_heli_max16)
      if(allocated(acswdnt)) deallocate(up_heli_min)
      if(allocated(acswdnt)) deallocate(up_heli_min16)
      if(allocated(acswdnt)) deallocate(up_heli_max02)
      if(allocated(acswdnt)) deallocate(up_heli_min02)
      if(allocated(acswdnt)) deallocate(up_heli_max03)
      if(allocated(acswdnt)) deallocate(up_heli_min03)
      if(allocated(acswdnt)) deallocate(rel_vort_max)
      if(allocated(acswdnt)) deallocate(rel_vort_max01)
      if(allocated(acswdnt)) deallocate(rel_vort_maxhy1)
      if(allocated(acswdnt)) deallocate(wspd10umax)
      if(allocated(acswdnt)) deallocate(wspd10vmax)
      if(allocated(acswdnt)) deallocate(refdm10c_max)
      if(allocated(acswdnt)) deallocate(hail_max2d)
      if(allocated(acswdnt)) deallocate(hail_maxk1)
      if(allocated(acswdnt)) deallocate(grpl_max)
      if(allocated(acswdnt)) deallocate(up_heli)
      if(allocated(acswdnt)) deallocate(up_heli16)
      if(allocated(acswdnt)) deallocate(ltg1_max)
      if(allocated(acswdnt)) deallocate(ltg2_max)
      if(allocated(acswdnt)) deallocate(ltg3_max)
      if(allocated(acswdnt)) deallocate(nci_ltg)
      if(allocated(acswdnt)) deallocate(nca_ltg)
      if(allocated(acswdnt)) deallocate(nci_wq)
      if(allocated(acswdnt)) deallocate(nca_wq)
      if(allocated(acswdnt)) deallocate(nci_refd)
      if(allocated(acswdnt)) deallocate(nca_refd)

! CRA
      if(allocated(acswdnt)) deallocate(REF_10CM)
      if(allocated(acswdnt)) deallocate(REFC_10CM)
      if(allocated(acswdnt)) deallocate(REF1KM_10CM)
      if(allocated(acswdnt)) deallocate(REF4KM_10CM)
! CRA
      if(allocated(acswdnt)) deallocate(U10mean)
      if(allocated(acswdnt)) deallocate(V10mean)
      if(allocated(acswdnt)) deallocate(SPDUV10mean)
      if(allocated(acswdnt)) deallocate(SWRADmean)
      if(allocated(acswdnt)) deallocate(SWNORMmean)
      if(allocated(acswdnt)) deallocate(SNFDEN)
      if(allocated(acswdnt)) deallocate(SNDEPAC)

!
!     FROM MASKS
!
      if(allocated(acswdnt)) deallocate(hbm2)
      if(allocated(acswdnt)) deallocate(sm)
      if(allocated(acswdnt)) deallocate(sice)
      if(allocated(acswdnt)) deallocate(lmh)  ! real
      if(allocated(acswdnt)) deallocate(lmv)  ! real
      if(allocated(acswdnt)) deallocate(gdlat)
      if(allocated(acswdnt)) deallocate(gdlon)
      if(allocated(acswdnt)) deallocate(dx)
      if(allocated(acswdnt)) deallocate(dy)
      if(allocated(acswdnt)) deallocate(htm)
      if(allocated(acswdnt)) deallocate(vtm)

! add GFIP ICING
      if(allocated(acswdnt)) deallocate(icing_gfip)
      if(allocated(acswdnt)) deallocate(icing_gfis)

! add GTG turbulence
      if(allocated(acswdnt)) deallocate(catedr)
      if(allocated(acswdnt)) deallocate(mwt)
      if(allocated(acswdnt)) deallocate(gtg)

!
      if (gocart_on) then
! Deallocate GOCART fields
! vrbls4d
        if(allocated(acswdnt)) deallocate(dust)
        if(allocated(acswdnt)) deallocate(salt)
        if(allocated(acswdnt)) deallocate(soot)
        if(allocated(acswdnt)) deallocate(waso)
        if(allocated(acswdnt)) deallocate(suso)
        if(allocated(acswdnt)) deallocate(pp25)
        if(allocated(acswdnt)) deallocate(pp10)
! vrbls3d
        if(allocated(acswdnt)) deallocate(ext)
        if(allocated(acswdnt)) deallocate(asy)
        if(allocated(acswdnt)) deallocate(ssa)
        if(allocated(acswdnt)) deallocate(sca)
        if(allocated(acswdnt)) deallocate(duem)
        if(allocated(acswdnt)) deallocate(dusd)
        if(allocated(acswdnt)) deallocate(dudp)
        if(allocated(acswdnt)) deallocate(duwt)
        if(allocated(acswdnt)) deallocate(tot_dust)
        if(allocated(acswdnt)) deallocate(vis_dust)
        if(allocated(acswdnt)) deallocate(dusv)
        if(allocated(acswdnt)) deallocate(suem)
        if(allocated(acswdnt)) deallocate(susd)
        if(allocated(acswdnt)) deallocate(sudp)
        if(allocated(acswdnt)) deallocate(suwt)
        if(allocated(acswdnt)) deallocate(ocem)
        if(allocated(acswdnt)) deallocate(ocsd)
        if(allocated(acswdnt)) deallocate(ocdp)
        if(allocated(acswdnt)) deallocate(ocwt)
        if(allocated(acswdnt)) deallocate(ocsv)
        if(allocated(acswdnt)) deallocate(bcem)
        if(allocated(acswdnt)) deallocate(bcsd)
        if(allocated(acswdnt)) deallocate(bcdp)
        if(allocated(acswdnt)) deallocate(bcwt)
        if(allocated(acswdnt)) deallocate(bcsv)
        if(allocated(acswdnt)) deallocate(ssem)
        if(allocated(acswdnt)) deallocate(sssd)
        if(allocated(acswdnt)) deallocate(ssdp)
        if(allocated(acswdnt)) deallocate(sswt)
        if(allocated(acswdnt)) deallocate(sssv)
        if(allocated(acswdnt)) deallocate(dpres)
        if(allocated(acswdnt)) deallocate(rhomid)
! vrbls2d
        if(allocated(acswdnt)) deallocate(tot_edust)
        if(allocated(acswdnt)) deallocate(dusmass)
        if(allocated(acswdnt)) deallocate(ducmass)
        if(allocated(acswdnt)) deallocate(dusmass25)
        if(allocated(acswdnt)) deallocate(ducmass25)
        if(allocated(acswdnt)) deallocate(susmass)
        if(allocated(acswdnt)) deallocate(sucmass)
        if(allocated(acswdnt)) deallocate(susmass25)
        if(allocated(acswdnt)) deallocate(sucmass25)
        if(allocated(acswdnt)) deallocate(ocsmass)
        if(allocated(acswdnt)) deallocate(occmass)
        if(allocated(acswdnt)) deallocate(ocsmass25)
        if(allocated(acswdnt)) deallocate(occmass25)
        if(allocated(acswdnt)) deallocate(bcsmass)
        if(allocated(acswdnt)) deallocate(bccmass)
        if(allocated(acswdnt)) deallocate(bcsmass25)
        if(allocated(acswdnt)) deallocate(bccmass25)
        if(allocated(acswdnt)) deallocate(sssmass)
        if(allocated(acswdnt)) deallocate(sscmass)
        if(allocated(acswdnt)) deallocate(sssmass25)
        if(allocated(acswdnt)) deallocate(sscmass25)
        if(allocated(acswdnt)) deallocate(dustcb)
        if(allocated(acswdnt)) deallocate(occb)
        if(allocated(acswdnt)) deallocate(bccb)
        if(allocated(acswdnt)) deallocate(sulfcb)
        if(allocated(acswdnt)) deallocate(pp25cb)
        if(allocated(acswdnt)) deallocate(pp10cb)
        if(allocated(acswdnt)) deallocate(sscb)
        if(allocated(acswdnt)) deallocate(dustallcb)
        if(allocated(acswdnt)) deallocate(ssallcb)
        if(allocated(acswdnt)) deallocate(dustpm)
        if(allocated(acswdnt)) deallocate(sspm)
      endif
!
! HWRF RRTMG output 
      if(allocated(acswdnt)) deallocate(acswupt)
      if(allocated(acswdnt)) deallocate(swdnt)
      if(allocated(acswdnt)) deallocate(acswdnt)
      
      end
